# Generated by Django 2.1.2 on 2018-12-06 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('class_no', models.IntegerField(default=0)),
                ('is_activated', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
