# Generated by Django 2.1.2 on 2018-10-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField(default='{}')),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trash',
                'verbose_name_plural': 'Trashes',
            },
        ),
    ]
