# Generated by Django 2.1.2 on 2018-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YConstant',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
    ]
